name: Setup Tizen CLI
description: This action installs the Tizen CLI and adds it to the PATH

inputs:
  version:
    description: The version of the Tizen CLI to install, eg. '5.6'
    required: true
  installation-path:
    description: The directory to install the Tizen CLI
    required: false
    default: ${{ github.workspace }}/tizen-studio

runs:
  using: "composite"
  steps:
    - name: Prepare environment variables
      shell: bash
      run: |
        echo "TIZEN_SDK_URL=https://download.tizen.org/sdk/Installer/tizen-studio_${{ inputs.version }}/web-cli_Tizen_Studio_${{ inputs.version }}_ubuntu-64.bin" >> $GITHUB_ENV
        echo "TIZEN_SDK_FILENAME=tizen-studio-installer.bin" >> $GITHUB_ENV

    - name: Cache Tizen SDK installer
      id: cache-tizen-sdk
      uses: actions/cache@v4
      with:
        path: ${{ env.TIZEN_SDK_FILENAME }}
        key: ${{ runner.os }}-tizen-sdk-${{ inputs.version }}

    - name: Download Tizen SDK installer
      shell: bash
      if: steps.cache-tizen-sdk.outputs.cache-hit != 'true'
      run: curl -Lo $TIZEN_SDK_FILENAME "$TIZEN_SDK_URL"

    - name: Make Tizen SDK executable
      shell: bash
      run: chmod a+x $TIZEN_SDK_FILENAME

    - name: Install Tizen Studio
      shell: bash
      run: ./${{ env.TIZEN_SDK_FILENAME }} --accept-license "${{ inputs.installation-path }}"

    - name: Export Tizen Studio path
      shell: bash
      run: echo "${{ inputs.installation-path }}/tools/ide/bin" >> $GITHUB_PATH

    - name: Log the Tizen CLI version
      shell: bash
      run: tizen version
