name: Seteup Tizen Security Profile
description: Setup Tizen Security Profile for application signing

inputs:
  author-key:
    description: Key for author certificate (.p12 file) base64 encoded
    required: true
  author-password:
    description: Password for author certificate (plain text)
    required: true
  distributor-key:
    description: Key for distributor certificate (.p12 file) base64 encoded
    required: true
  distributor-password:
    description: Password for distributor certificate (plain text)
    required: true
  profile-name:
    description: Name of the security profile to create
    required: false
    default: "game"

runs:
  using: "composite"
  steps:
    - name: Install gnome-keyring
      shell: bash
      run: sudo apt-get install -y gnome-keyring

    - name: Create certificates directory
      shell: bash
      run: mkdir -p ${{ github.action_path }}/certs

    - name: Prepare certificate files
      id: certificates
      shell: bash
      run: |
        AUTHOR_KEY_PATH="${{ github.action_path }}/certs/author.p12"
        DISTRIBUTOR_KEY_PATH="${{ github.action_path }}/certs/distributor.p12"

        echo "${{ inputs.author-key }}" | base64 -d > "$AUTHOR_KEY_PATH"
        echo "${{ inputs.distributor-key }}" | base64 -d > "$DISTRIBUTOR_KEY_PATH"

        echo "author_key_path=$AUTHOR_KEY_PATH" >> $GITHUB_OUTPUT
        echo "distributor_key_path=$DISTRIBUTOR_KEY_PATH" >> $GITHUB_OUTPUT

    - name: Start persistent DBUS session
      shell: bash
      run: |
        DBUS_ADDRESS=$(dbus-daemon --session --fork --print-address) 
        echo "DBUS_SESSION_BUS_ADDRESS=$DBUS_ADDRESS" >> $GITHUB_ENV

    - name: Setup GNOME keyring and Tizen security profile
      shell: bash
      run: |
        echo "" | gnome-keyring-daemon --unlock
        tizen security-profiles add -n "${{ inputs.profile-name }}" -a "${{ steps.certificates.outputs.author_key_path }}" -p "${{ inputs.author-password }}" -d "${{ steps.certificates.outputs.distributor_key_path }}" -dp "${{ inputs.distributor-password }}"
        tizen security-profiles list | grep -q "${{ inputs.profile-name }}"
