name: Add Tizen Security Profile
description: Add Tizen Security Profile

inputs:
  author-ca:
    description: CA for author certificate (.crt file) base64 encoded
    required: true
  author-key:
    description: Key for author certificatea (.p12 file) base64 encoded
    required: true
  author-password:
    description: Password for author certificate (plain text)
    required: true
  distributor-ca:
    description: CA for distributor certificate (.crt file) base64 encoded
    required: true
  distributor-key:
    description: Key for distributor certificate (.p12 file) base64 encoded
    required: true
  distributor-password:
    description: Password for distributor certificate (plain text)
    required: true

runs:
  using: "composite"
  steps:
    - name: Install gnome-keyring
      shell: bash
      run: sudo apt-get install -y gnome-keyring

    - name: Create certificates directory
      shell: bash
      run: |
        mkdir -p ${{ github.action_path }}/certs

    - name: Set environment variables for file paths
      shell: bash
      run: |
        # Set file paths as environment variables
        echo "AUTHOR_KEY_PATH=${{ github.action_path }}/certs/author.p12" >> $GITHUB_ENV
        echo "DISTRIBUTOR_KEY_PATH=${{ github.action_path }}/certs/distributor.p12" >> $GITHUB_ENV
        echo "AUTHOR_CA_PATH=${{ github.action_path }}/certs/author-ca.crt" >> $GITHUB_ENV
        echo "DISTRIBUTOR_CA_PATH=${{ github.action_path }}/certs/distributor-ca.crt" >> $GITHUB_ENV

        # Save passwords as environment variables directly
        echo "AUTHOR_PASSWORD=${{ inputs.author-password }}" >> $GITHUB_ENV
        echo "DISTRIBUTOR_PASSWORD=${{ inputs.distributor-password }}" >> $GITHUB_ENV

    - name: Decode base64 certificates and keys
      shell: bash
      run: |
        echo "${{ inputs.author-ca }}" | base64 -d > ${{ env.AUTHOR_CA_PATH }}
        echo "${{ inputs.author-key }}" | base64 -d > ${{ env.AUTHOR_KEY_PATH }}

        echo "${{ inputs.distributor-ca }}" | base64 -d > ${{ env.DISTRIBUTOR_CA_PATH }}
        echo "${{ inputs.distributor-key }}" | base64 -d > ${{ env.DISTRIBUTOR_KEY_PATH }}

    - name: Get Tizen profiles path
      shell: bash
      run: |
        GLOBAL_PROFILES_PATH="$(tizen cli-config -l | grep "default.profiles.path" | cut -d'=' -f2)"
        echo "TIZEN_PROFILES_PATH=$GLOBAL_PROFILES_PATH" >> $GITHUB_ENV

    - name: Update tizen security profile
      shell: bash
      run: |
        cat > ~/package.sh <<EOF
        echo "" | gnome-keyring-daemon --unlock
        tizen security-profiles add -n game -a ${{ env.AUTHOR_KEY_PATH }} -p ${{ env.AUTHOR_PASSWORD }} -d ${{ env.DISTRIBUTOR_KEY_PATH }} -dp ${{ env.DISTRIBUTOR_PASSWORD }}
        ls $GITHUB_WORKSPACE/app/web/dist/.buildResult
        tizen package -t wgt -o out -- $GITHUB_WORKSPACE/app/web/dist/.buildResult
        EOF

    - name: Run package.sh
      shell: bash
      run: |
        chmod +x ~/package.sh
        dbus-run-session -- ~/package.sh
