name: Mixed inputs
on:
  workflow_dispatch:
  push:
    branches:
      - nx-release-zip

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo 'Hello World'
