name : Tizen Build

on:
  workflow_dispatch:
  push:
    branches:
      - tizen-build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup node and pnpm
        uses: ./.github/actions/setup-node-and-pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the application
        run: npx nx build web --verbose

      - name: Get the absolute path of the dist folder
        id: get-dist-folder-path
        run: echo "dist-folder-path=$(pwd)/app/web/dist" >> $GITHUB_OUTPUT

      - name: Build Tizen app
        id: tizen-build-action
        uses: sourcetoad/tizen-build-action@v1.1.1
        with:
          project-dir: ${{ steps.get-dist-folder-path.outputs.dist-folder-path }}
          author-key: "MIIK3QIBAzCCCpYGCSqGSIb3DQEHAaCCCocEggqDMIIKfzCCAxMGCSqGSIb3DQEHAaCCAwQEggMAMIIC/DCCAvgGCyqGSIb3DQEMCgECoIICpTCCAqEwGwYKKoZIhvcNAQwBAzANBAjHcyGMfsjumQIBFASCAoDgj4JtCDztNyhwly4Uu3EfDVmXxUxabm8Wh6cT4syutgwOHJ1wwle46c78YgmAjT/C7iJsXS54jrH3NQTInTEEzMru/6QfXveNTqRHDku1IcMGnvQGuq3qxDDuKaYL1KatUYY3DUaOK6UwxT8xjkRsQIZw/MosvkY7ApO2XOOsz04bRig7Eb8Ymr/hcChWb4G7yD7pk+WxEl1Yn6jBttWeV3C/cmFHRm4oqu1bqJid8Qj48+8qEQkx2Fy6jz3MijMez5TStP6CVMHQGLDL9BNKjFpLutAEjTiTB/OaFbM+NDlYIs8QXvr3/1PUQRM2yMxphHT9wABCZKD42fqmzq9l8UtWEkN6DysmlkK35RtPETknNp2/ewDBGJHziMHFjmW6lwwrlrEgAK07Ofd7RnWk2K8ppB8SNc7eHnZ9VIafs1Qc6Di4WBrzI3bLuuhP5hZxnQnKpevCWXR1kAY2g+wnefTnzuvDzeiXw484zW6bj4qNYhI9eTmNVgScwDKLte2Sjg5egOpuhsifLd8/ruwDJg+6aSKOEKVqCyCf5TpsqWjp1z14imuikWlwrLOwoj+ZfRBb+dPebv3/EHexnPPOoO1bfoaeZM3qlRsc2fnbD0hAXNOF7/vz/UgqH0BkG+unH4S2LgsHaM/Anol1LOBlEFY0F+mzCnYpfzaRhCnigHPxyzrpcVEidgycbTLqomp47nKGaa2G/pq0IJfvoFn3ONZO48A8AAl6Vnna4Dg6qOVci/MqIh1GvXNpx0HmBQ6EU0hTmnBSQlA6PCv9FRie8rNMCvTHLKhDArIEJSt9bI3aZwuUkvA0B9MmyMeW5+BFicIPRbjJzn1jB2eb+6ZpMUAwGwYJKoZIhvcNAQkUMQ4eDABnAG8AdABoAGEAbTAhBgkqhkiG9w0BCRUxFAQSVGltZSAxNzMwNDM3ODU5NTA5MIIHZAYJKoZIhvcNAQcGoIIHVTCCB1ECAQAwggdKBgkqhkiG9w0BBwEwKQYKKoZIhvcNAQwBBjAbBBR5IGy02U70/1FMTRw1yCGQ7+d3QQIDAMNQgIIHEJpN82vLiKn5wWHdaNOndnjN9IbPirbcl+kv6LowVVZjk8cEzfuDnP/5JU/kBpHIuiZbi0FxF8pmhHuetKYQ+hGPrWEUS54LHrX6lCzP1sD9dZHdr+OFKyPA1IGhCV2hu8YNVV+JOGYhJue2eakH1fPwZfxlqQzUSWaH+fpwdQRJwj1TdYPwwsA99FGgjyey1cIZKh7IjyhP26VHxJdVVSmoRPkUtUYazLuDx/PPYGvdeD1Exwwz/+co6wB/4rRIq4CYRpR5WzXzYS3FgiQQElO/8eqyraJNyjvSrCvgwB6bGhfVapwCEF5CNmhJKRgr9adkWlBX8tD0dF4rADu3qYq6Yr7fo8lNUOy509JQN6L2S06eQ9IzCkC5CQjAAxhasCViz1siZPgTmeIIyRRAs1j791Uq4ilfL2lsCUiJF+K083Vfbs7q9EwAkv7gKd3rBHkvQ96gbW86Qt/RK8ohMd5xqHEuZupL4e8X1sgzplA5AzS9KkKUqkKO1CL/wt7e3J3HP4MwJUMc3X1H5jHePgG1k5po4SQ7EZQdMe+84m5X8aKnAHT5X+WjkILwGX3ZagWL8kEnSQU6vCoz8r6dyIND6u8kVbEk4KZ6wX8Yl+KDCFNmhDy1qxWqWireaINwkLXhYB9Tf9jjGkYtCtKAcwGC5U5yAA2cCmkgQarON1gztxTpSkVm6P4pToMjmtp++hlijB+L45jhynYvM+3ddb+65eoabKC2y765nU+dNe5z6nx6YEkGv8dH7RmPXKcFlgJAXITFOCk34DZNxrx/wzqVSHzxhWb2GQS75H8ZJirr6mn3NPFQ9J6Zcrpf31IF8LQEpx7waw5cw5fQxry8OU8U6H3l9Jtnbi0yPmuauhppOmYHdZ15EYVk2dLbmi4pLuNlHEkCgm8+S0hZ+Ccl6lNLuqJUuExixXs9/hmhMMdBClBGHuTlJBmmK1P9hZx/32PhfUYvSEuTq94dmKJjj0joTkkOrgZOOnEm8+4HKDlI/+fZ3zEeSABd30NABSmVC/HDC+kDrlpFJ8j8FaSPCPqG3VFcMigTwbb4EoNf8D9sNvQrTP86whZV5X1aRJwmzxWLFFgVHncbMdwqd6RoYImVEp6dpBqc8qI0v32Go430X2rIjQHfcTLuRkuTIjTOkW/tkVqb2bebsPO4ykPiJQnChly8QuLavqZc8pQbAY1hh3OErqHZX9jgh2Q/JsFGodEmdbgKUA84QKOjwgd8JnPaIoSG8zchc6CSvjgQzwIkO4qD0UQfYsJNDW3qmYvZqLTgUVjfqV+hvZ1/7oNsV7OCED+cFSepGsOcPLJfyXgAlDjY0I6BIvG06pRqstoR9bElT9mNc0YN01dTw21EJDnMZitOZID6eTSOCqGGNy7PHCNB370Gf+Sa2nf1wWuYS1Xj0KVoflL84SF9OGFekRnrzcfGUlQ5gBynHs1Aa+zq7sBSqHa9dDqz776imL3CeAWalkJPArvuiQ6eDbYNFzAVoo1xczd6/qxez5kMG2AHmV6RPY39cabCMwKtLEdGgf7VIplD6UuE8EO4i5KnIXKZMIsXHympA3NMZbpEsCc2Sveu3ATPQeSxWDXeNbmRtFe7CmoiP2/GfH+7X268Jrb12oCE6PaUfgR4nMjieb9ZO1QyNiHTViCMtkzT5y6bjGzQ8vLXb8FkDTnp+5KvZ1GhA243+8Oou3+snsas0mT1io8hSOENK1cihU8ybRMftkBKB3w5M3lrH1CNLqglMCrGFvFknCrAqttsKMguHgZnXzyk14b1WEqW+CnPvDWEVaxDZJZSYENp1yAXLKQOOWKKTXFQoDAiljmDgIG3cm8429Oc1OtgB2KpfGaqA+UqH+l7n23cHNe/iOl2inlwPTcFnq6mTKPwKk1AR8Hnupn/lYB4HAfE2rwQW8XItDbglw2O6IRcgaS1zjQT43n+9k5tMpV1hcAYE1EtljnzFy/DIt54L+JbgW3GqowVym7hPNXWjYnH6jMVa+JbcdqplPt2j62qyVGMWH3cKt5UPD1Gd8cTIDVtI80mZFFqmB5p4iTJHM5XoNXEuoKVeMPMEec9/SX8HUYWOixC6wH71XBho94hF4Nx9jVhlVfPX32ONNetNJ7S3EI3gIySTW0H0gFTgysCJAewu4IV3ZiXkOHJbB/bvhp9LKdzQQ9oBkjvUv9vmaybAsF3EZKx4jbrQMoVdLRwFduZnRgwznLfzMFL4/4YR+IMWLgwHeI8mk/++SxwRUosi7W4rWNWfBAn9FqiF3tXfMpAMCQR7xiTkbTHYIhU2DbZIvwSktOP4Pe0fmQfYoxV7h0EcKoQtfyjPACK4v8ABY/2ZM7eV5U6QxS0ZHcE4V749pWIAa7kPIQ55auqfC7C4fNXkEos5uxAiFGgCSUoSb402KUo7cd7EDl0MD4wITAJBgUrDgMCGgUABBRFGCRr/IMVZgMU8bCIkk9yom79GwQUUipiCPr3jAFInEuKsLw8ab8chGUCAwGGoA=="
          author-password: "MTIzNDU2NzhBYmNACg=="

      # - name: Prepare Tizen CLI
      #   uses: ./.github/actions/perpare-tizen-cli
      #
      # - name: Add Tizen Security Profile
      #   uses: ./.github/actions/add-tizen-security-profile
      #   with:
      #     # author-cert: ${{ secrets.TIZEN_AUTHOR_CERT }}
      #     # author-key: ${{ secrets.TIZEN_AUTHOR_KEY }}
      #     # author-password: ${{ secrets.TIZEN_AUTHOR_PASSWORD }}
      #     # author-ca: ${{ secrets.TIZEN_AUTHOR_CA }}
      #     # distributor-key: ${{ secrets.TIZEN_DISTRIBUTOR_KEY }}
      #     # distributor-password: ${{ secrets.TIZEN_DISTRIBUTOR_PASSWORD }}
      #     author-cert: ""
      #     author-key: ""
      #     author-password: ""
      #     author-ca: ""
      #     distributor-key: ""
      #     distributor-password: ""
      #
      # - name: List Tizen Security Profiles
      #   run: tizen security-profiles list


